### ISSUE TITLE
[Security] New user login lets other session switch identity

### ISSUE THREAD

**Issue by verymilan** [Flomp/wanderer#247]
Okey, this one is interesting. I now have three unique users on my instance, each have their own unique tokens as far as i can see in PocketBase, right now I am only aware of one of them causing this, but if they login, my session suddenly belongs to their identity. If i log out, they are logged out as well.

Edit: does not always seem to happen that all logins are devalidated on logout as described above... . This time as they logged out, i remain to be logged in as their identity.

**Comment by slothful-vassal** [comment]
This appears on different machines / in different browser sessions?

**Comment by verymilan** [comment]
Yes, i was considering a public tchncs.de instance and those are first testers on it. :) [(german) discussion on mastodon.](https://social.tchncs.de/@milan/114302617973987884)

**Comment by Flomp** [comment]
Found the issue:
I used a global, shared PocketBase instance across requests. Meaning if a second request came to the server while the first was still being handled, the second one received the auth of the first. I just published v0.16.4, which fixes this.

**Comment by verymilan** [comment]
sounds promising (among with the other recent things youve addressed) - thank you!

**Comment by foss-** [comment]
Sadly this is not fully resolved. In 0.16.5 there was a situation where a new user saw their profile picture on top right along with their profile description but on the left side the profile of an existing users showed.
