### ISSUE TITLE
Search container is not coming up

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#25]
With version 0.2.0. when starting up fresh with ```docker compose up``` results in an 

```
dependency failed to start: container wanderer-search-1 is unhealthy
```

and an empty search folder. No other error is shown in the console even though i added ```MEILI_LOG_LEVEL: WARN```

**Comment by Flomp** [comment]
Oh god, I'm dumb...
I messed up the docker image latest tags. The issue is fixed now. Please repull.

**Comment by garbast** [comment]
Yes! It's working after the pull

**Comment by phil3741** [comment]
still having this issue on arm64 (Raspberry Pi)

tried several tags, and tried to remove and repull containers with no sucess.
