### ISSUE TITLE
Homepage search functionality not working

### ISSUE THREAD

**Issue by RobertClarke64** [Flomp/wanderer#330]
After the latest update (v.0.17.0), the homepage search doesn't seem to link to the right place any more. I can search for and click on walks, but it just leads to a 404 error. This issue can also be reproduced on the demo instance of wanderer (https://demo.wanderer.to).

<img width="578" alt="Image" src="https://github.com/user-attachments/assets/906ca947-5b9b-4be8-8a1c-03cc358b67d7" />

<img width="1433" alt="Image" src="https://github.com/user-attachments/assets/e3f41aa1-ed1f-4ae8-8a5b-1bff244b9a57" />

**Comment by CYBERNEURONES** [comment]
I have same issue ....

**Comment by Flomp** [comment]
Ah, sorry. My bad. Will be fixed in the next patch:

https://github.com/Flomp/wanderer/commit/8e3eea6216fe8ff8355789e34a429dce338c1571

**Comment by Flomp** [comment]
Fixed in v0.17.1

**Comment by Ra72xx** [comment]
I still have the problem in 0.17.1. Whatever I search for, nothing is found: 

<img width="1261" height="650" alt="Image" src="https://github.com/user-attachments/assets/c38e29f4-e4a8-4397-8715-efda68d63775" />

**Comment by RobertClarke64** [comment]
@Ra72xx your issue is different to this one.

The issue here was that the search on the trails page was working fine. But while the homepage search would find walks, when clicked would lead to a 404.

**Comment by Ra72xx** [comment]
I noticed that the problem only occured on my laptop, the mobile phone was working fine. So I logged out of my Wanderer session, cleared all caches and logged in again, and now the search works. So - sorry for the noise.

**Comment by CYBERNEURONES** [comment]
For me it's fixed.
Thanks.
https://aventures.cyber-neurones.org/
