### ISSUE TITLE
Summit Book - Elevation Gain & Loss extracted from gpx track are wrong.

### ISSUE THREAD

**Issue by resoli** [Flomp/wanderer#407]
Adding an element with a gpx track to the summit book results in wrong elevation metadata showing (3000m instead of 1000m, maybe metadata are wrongly reported in feet?). Example: See: https://giretti.gatti.ninja/trail/view/@rresoli/e0f3e2f18bcfbac

In the following image you see metadata extracted from the trail and the very same track added as summit log. Metadata other than elevation are aligned.

<img width="939" height="374" alt="Image" src="https://github.com/user-attachments/assets/5c15194b-8eec-493b-9711-86f99c0de045" />

**Comment by Ra72xx** [comment]
There seems to be something wrong with the height calculation. I have such issues, too:
#406 (simply completely wrong height, more then 2x in my case) 
#380 (parts of the trip which were not recorded in the gpx file are included in the height calculation nevertheless)
That's a shame for this otherwise promising piece of software, as reliable tour data seems to be a 'must'. Let's hope that a fix will be found.

**Comment by resoli** [comment]
@Ra72xx in my case elevation data calculated by OsmAnd (which I used to record the track) more or less corresponds to Wanderer calculated for the trail: 1056m Gain, 1053m Loss . 

Wanderer is still young, but I like very much the base philosophy (no surveillance, self-hosting, activity pub enabled), so I can definitely live with temporary problems.

**Comment by Ra72xx** [comment]
I also like Wanderer very much. But I currently got the feeling that the values it calculates for different kind of route statistics are not always reliable. Your example is different than mine, to be sure, but not too unsimiliar - it's just that the summit log is affected and not the original track. I will try that, too.

**Comment by lu-x** [comment]
I can confirm, in my case it's 220 in the route vs 178 in the summit log (same gpx track)

**Comment by Flomp** [comment]
Fixed by https://github.com/Flomp/wanderer/commit/097ecd409dcf58a3bf419e4c2136f541e56485e9.

**Comment by Flomp** [comment]
Fixed in v0.18.0.

**Comment by lu-x** [comment]
I still get a diff with v0.18.1

same track:

route:
<img width="1024" height="71" alt="Image" src="https://github.com/user-attachments/assets/23c49a76-d178-4c4a-beac-ca502bf8d6cf" />

summit log:
<img width="640" height="175" alt="Image" src="https://github.com/user-attachments/assets/37e8c6ab-a229-4301-be09-e2fb21ca30b3" />

My Garmin Edge shows me: 322m up, 318m down
